
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ebook_website.Models
{

using System;
    using System.Collections.Generic;
    
public partial class conctact
{

    public int id { get; set; }

    public string Nom { get; set; }

    public string email { get; set; }

    public string Tel { get; set; }

    public string contenu { get; set; }

}

}
