
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ebook_website.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Livre
{

    public int ID_Livre { get; set; }

    public string Titre { get; set; }

    public string Auteur { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> Date_Publication { get; set; }

    public Nullable<System.DateTime> Date_Edition { get; set; }

    public Nullable<int> ID_Categorie { get; set; }

    public string Image { get; set; }

    public string PDF { get; set; }



    public virtual Categorie Categorie { get; set; }

}

}
