# Generated by Django 4.0.4 on 2022-06-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('Id_categorie', models.IntegerField(primary_key=True, serialize=False)),
                ('name_categorie', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('TEL', models.IntegerField()),
                ('Contenu', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('Nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=20)),
                ('Auteur', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=30)),
                ('Date_publication', models.DateTimeField()),
                ('Date_Edition', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('Pdf', models.FileField(upload_to='')),
                ('Id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.categorie')),
            ],
        ),
    ]
